---
title: "hw04"
author: "Diego A. Dulanto"
date: "3/9/2021"
output: 
  github_document: default
  html_document: 
    theme: paper
---

```{r setup}
library(haven)
library(tidyverse)
library(ggplot2)
library(readr)
library(tibble)
library(ggdist)
library(gridExtra)
```



```{r}
here::here("data", "immigrant_data_2000.sav")

(immigrant_data <- haven::read_sav(
  here::here("data", "immigrant_data_2000.sav")
)
)

##Renaming columns

colnames(immigrant_data)[colnames(immigrant_data) == "V1"] <- "Month of Admission"
colnames(immigrant_data)[colnames(immigrant_data) == "V2"] <- "Year of Admission"
colnames(immigrant_data)[colnames(immigrant_data) == "V3"] <- "Country of Birth"
colnames(immigrant_data)[colnames(immigrant_data) == "V4"] <- "Age"
colnames(immigrant_data)[colnames(immigrant_data) == "V5"] <- "Country of Last Permanent Residence"
colnames(immigrant_data)[colnames(immigrant_data) == "V6"] <- "Marital Status"
colnames(immigrant_data)[colnames(immigrant_data) == "V7"] <- "State of Intended Residence"
colnames(immigrant_data)[colnames(immigrant_data) == "V8"] <- "Metropolitan Area of Intended Residence"
colnames(immigrant_data)[colnames(immigrant_data) == "V9"] <- "Labor Certification"
colnames(immigrant_data)[colnames(immigrant_data) == "V10"] <- "Occupation"
colnames(immigrant_data)[colnames(immigrant_data) == "V11"] <- "Sex"
colnames(immigrant_data)[colnames(immigrant_data) == "V12"] <- "Country of Chargeability"
colnames(immigrant_data)[colnames(immigrant_data) == "V13"] <- "Type of Case"
colnames(immigrant_data)[colnames(immigrant_data) == "V14"] <- "Nonimmigrant class of entry"
colnames(immigrant_data)[colnames(immigrant_data) == "V15"] <- "Nonimmigrant year of entry"
colnames(immigrant_data)[colnames(immigrant_data) == "V16"] <- "Immigrant class of admission"
colnames(immigrant_data)[colnames(immigrant_data) == "V17"] <- "Principal vs. Derivative Class of Admission"


print(immigrant_data)

```

```{r}
#Structuring Data

as_tibble(immigrant_data)

str(immigrant_data)
```


```{r}
#Summarizing Data
immigrant_data %>%
  summarise(`Month of Admission`, `Country of Birth`, Age)

immigrant_data %>%
  group_by(`Country of Birth`)
  

```



```{r fig.height = 10, fig.width = 15, fig.align = "center"}
#Plotting Data

immigrant_data
        col_types = cols(
          'Month of Admission' = col_double(),
          'Year of Admission' = col_double(),
          'Country of Birth' = col_double(),
          'Age' = col_double(),
          'Country of Last Permanent Residence' = col_character(),
          'Marital Status' = col_double(),
          'State of Intended Residence' = col_double(),
          'Metropolitan Area of Intended Residence' = col_double(),
          'Labor Certification' = col_double(),
          'Occupation' = col_double(),
          'Sex' = col_double(),
          'Country of Chargeability' = col_double(),
          'Type of Case' = col_double(),
          'Nonimmigrant class of entry' = col_double(),
          'Nonimmigrant year of entry' = col_double(),
          'Immigrant class of admission' = col_double(),
          'Principal vs. Derivative Class of Admission' = col_double())

print(immigrant_data)
        
immigrant_data %>%
  select("Month of Admission", "Country of Birth") %>%
  ggplot() +
  aes(x = "Month of Admission", y = "Country of Birth") +
  geom_jitter(alpha = .005) +
  theme_classic()


```


