---
title: "hw04"
author: "Diego A. Dulanto"
date: "`r format(Sys.Date(), '%b %d %Y')`"
output:
    html_document:
        theme: paper
    github_document: default
editor_options: 
  chunk_output_type: console
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Final Project Introduction


```{r load packages, include=FALSE}
library(haven)
library(tidyverse)
library(ggplot2)
library(readr)
library(tibble)
library(ggdist)
library(gridExtra)
```



```{r importing data}
here::here("data", "immigrant_data_2000.sav")

(immigrant_data <- haven::read_sav(
  here::here("Final Project", "data", "immigrant_data_2000.sav")
)
)

## Renaming columns

colnames(immigrant_data)[colnames(immigrant_data) == "V1"] <- "Month_of_Admission"
colnames(immigrant_data)[colnames(immigrant_data) == "V2"] <- "Year_of_Admission"
colnames(immigrant_data)[colnames(immigrant_data) == "V3"] <- "Country_of_Birth"
colnames(immigrant_data)[colnames(immigrant_data) == "V4"] <- "Age"
colnames(immigrant_data)[colnames(immigrant_data) == "V5"] <- "Country_of_Last_Permanent_Residence"
colnames(immigrant_data)[colnames(immigrant_data) == "V6"] <- "Marital_Status"
colnames(immigrant_data)[colnames(immigrant_data) == "V7"] <- "State_of_Intended_Residence"
colnames(immigrant_data)[colnames(immigrant_data) == "V8"] <- "Metropolitan_Area_of_Intended_Residence"
colnames(immigrant_data)[colnames(immigrant_data) == "V9"] <- "Labor_Certification"
colnames(immigrant_data)[colnames(immigrant_data) == "V10"] <- "Occupation"
colnames(immigrant_data)[colnames(immigrant_data) == "V11"] <- "Sex"
colnames(immigrant_data)[colnames(immigrant_data) == "V12"] <- "Country_of_Chargeability"
colnames(immigrant_data)[colnames(immigrant_data) == "V13"] <- "Type_of_Case"
colnames(immigrant_data)[colnames(immigrant_data) == "V14"] <- "Nonimmigrant_class_of_entry"
colnames(immigrant_data)[colnames(immigrant_data) == "V15"] <- "Nonimmigrant_year_of_entry"
colnames(immigrant_data)[colnames(immigrant_data) == "V16"] <- "Immigrant_class_of_admission"
colnames(immigrant_data)[colnames(immigrant_data) == "V17"] <- "Principal_vs_Derivative_Class_of_Admission"


print(immigrant_data)
```

## Data Cleaning



```{r}
# Structuring Data

devtools::session_info()

```


```{r}
# Summarizing Data
immigrant_data %>%
  summarise(`Month of Admission`, `Country of Birth`, Age)


# WDG: `group_by() effects are only functional. In other words, this doesn't have any effect until you start manipulating the data.
immigrant_data %>%
  group_by(`Country of Birth`)
```



```{r}
# Plotting Data

immigrant_data

# WDG: Great you've created the col_types; however, its not applied to the data.
col_types <- cols(
  "Month of Admission" = col_double(),
  "Year of Admission" = col_double(),
  "Country of Birth" = col_double(),
  "Age" = col_double(),
  "Country of Last Permanent Residence" = col_character(),
  "Marital Status" = col_double(),
  "State of Intended Residence" = col_double(),
  "Metropolitan Area of Intended Residence" = col_double(),
  "Labor Certification" = col_double(),
  "Occupation" = col_double(),
  "Sex" = col_double(),
  "Country of Chargeability" = col_double(),
  "Type of Case" = col_double(),
  "Nonimmigrant class of entry" = col_double(),
  "Nonimmigrant year of entry" = col_double(),
  "Immigrant class of admission" = col_double(),
  "Principal vs. Derivative Class of Admission" = col_double()
)



# WDG: A title is very important when it comes to graphs. Try and answer the question: "What am I looking at?" when thinking of a title.
immigrant_data %>%
  select("Month of Admission", "Country of Birth") %>%
  ggplot() +
  aes(x = "Month of Admission", y = "Country of Birth") +
  geom_point(alpha = .05) +
  theme_classic()
```
